apiVersion: v1
kind: Service
metadata:
  name: colorapp
  namespace: colorapp
spec:
  type: LoadBalancer
  selector:
    app: colorapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000